version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/mattn/go-sqlite3
    versions:
    - 1.14.7
  - dependency-name: github.com/emersion/go-smtp
    versions:
    - 0.15.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: weekly
    time: "04:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redux-saga
    versions:
    - ">= 1.0.3.a, < 1.0.4"
  - dependency-name: redux-saga
    versions:
    - ">= 1.0.5.a, < 1.0.6"
